const RECIPES_AUXESIA = [
  {
    "region": "auxesia",
    "missionId": 1557,
    "missionName": "EX: 행성 식물 추출 응용",
    "job": "CRP",
    "rlvl": 727,
    "work": 2300,
    "quality": 24700,
    "durability": 70,
    "tag": "A-EX",
    "group": "A-EX",
    "category": "A-EX",
    "isSub": false
  },
  {
    "region": "auxesia",
    "missionId": 1558,
    "missionName": "EX: 소비 건축재 개발 지원",
    "job": "CRP",
    "rlvl": 728,
    "work": 9700,
    "quality": 17300,
    "durability": 70,
    "tag": "A-EX 2",
    "group": "A-EX 2",
    "category": "A-EX",
    "isSub": false
  },
  {
    "region": "auxesia",
    "missionId": 1559,
    "missionName": "EX: 위문용 고급술 양조",
    "job": "CRP",
    "rlvl": 729,
    "work": 8500,
    "quality": 19500,
    "durability": 60,
    "tag": "A-EX 3",
    "group": "A-EX 3",
    "category": "A-EX",
    "isSub": false
  },
  {
    "region": "auxesia",
    "missionId": 1560,
    "missionName": "EX+: 교외 거점 배급 지원",
    "job": "CRP",
    "rlvl": 771,
    "work": 7200,
    "quality": 24100,
    "durability": 80,
    "tag": "날씨제 1",
    "group": "날씨제 1",
    "category": "날씨제",
    "isSub": false
  },
  {
    "region": "auxesia",
    "missionId": 1561,
    "missionName": "EX+: 지속성 자원 개발 지원",
    "job": "CRP",
    "rlvl": 771,
    "work": 7600,
    "quality": 21100,
    "durability": 55,
    "tag": "날씨제 2",
    "group": "날씨제 2",
    "category": "날씨제",
    "isSub": false
  },
  {
    "region": "auxesia",
    "missionId": 1562,
    "missionName": "EX+: 궁극 효모 개발",
    "job": "CRP",
    "rlvl": 771,
    "work": 7800,
    "quality": 19600,
    "durability": 75,
    "tag": "날씨제 3",
    "group": "날씨제 3",
    "category": "날씨제",
    "isSub": false
  },
  {
    "region": "auxesia",
    "missionId": 1591,
    "missionName": "MASTER: 우주 완전식 탐구",
    "job": "CRP",
    "rlvl": 772,
    "work": 7700,
    "quality": 26000,
    "durability": 50,
    "tag": "MASTER 1",
    "group": "MASTER 1",
    "category": "MASTER",
    "isSub": false
  },
  {
    "region": "auxesia",
    "missionId": 1592,
    "missionName": "MASTER: 행성 식물 식용 연구",
    "job": "CRP",
    "rlvl": 773,
    "work": 7800,
    "quality": 25100,
    "durability": 60,
    "tag": "MASTER 2",
    "group": "MASTER 2",
    "category": "MASTER",
    "isSub": false
  },
  {
    "region": "auxesia",
    "missionId": 1593,
    "missionName": "MASTER: 우주 도구 개량 지원",
    "job": "CRP",
    "rlvl": 774,
    "work": 6900,
    "quality": 22100,
    "durability": 46,
    "tag": "MASTER 3",
    "group": "MASTER 3",
    "category": "MASTER",
    "isSub": false
  },
  {
    "region": "auxesia",
    "missionId": 1565,
    "missionName": "MASTER: 우주 도구 강화 지원",
    "job": "CRP",
    "rlvl": 775,
    "work": 7400,
    "quality": 26300,
    "durability": 80,
    "tag": "MASTER 4",
    "group": "MASTER 4",
    "category": "MASTER",
    "isSub": false
  }
];
