const RECIPES_PHAENNA = [
  {
    "region": "paenna",
    "missionId": 571,
    "missionName": "EX: 야외 활동용 비품 제작",
    "job": "CRP",
    "rlvl": 721,
    "work": 7800,
    "quality": 12200,
    "durability": 65,
    "tag": "A-EX",
    "group": "A-EX",
    "category": "A-EX"
  },
  {
    "region": "paenna",
    "missionId": 572,
    "missionName": "EX: 고성능 장인 도구 조달",
    "job": "CRP",
    "rlvl": 724,
    "work": 9700,
    "quality": 11600,
    "durability": 55,
    "tag": "A-EX 3",
    "group": "A-EX 3",
    "category": "A-EX"
  },
  {
    "region": "paenna",
    "missionId": 572,
    "missionName": "EX: 고성능 장인 도구 조달",
    "job": "CRP",
    "rlvl": 725,
    "work": 9700,
    "quality": 11600,
    "durability": 55,
    "tag": "A-EX 3 - 2",
    "group": "A-EX 3",
    "category": "A-EX"
  },
  {
    "region": "paenna",
    "missionId": 572,
    "missionName": "EX: 고성능 장인 도구 조달",
    "job": "CRP",
    "rlvl": 726,
    "work": 9700,
    "quality": 11600,
    "durability": 55,
    "tag": "A-EX 3 - 3",
    "group": "A-EX 3",
    "category": "A-EX"
  },
  {
    "region": "paenna",
    "missionId": 573,
    "missionName": "EX: 우주 운송용 포장재 제작",
    "job": "CRP",
    "rlvl": 721,
    "work": 5000,
    "quality": 12400,
    "durability": 35,
    "tag": "날씨제 1",
    "group": "날씨제 1",
    "category": "날씨제"
  },
  {
    "region": "paenna",
    "missionId": 573,
    "missionName": "EX: 우주 운송용 포장재 제작",
    "job": "CRP",
    "rlvl": 721,
    "work": 8700,
    "quality": 18000,
    "durability": 70,
    "tag": "날씨제 1",
    "group": "날씨제 1",
    "category": "날씨제"
  },
  {
    "region": "paenna",
    "missionId": 574,
    "missionName": "EX+: 임시 저장소 건설 지원",
    "job": "CRP",
    "rlvl": 742,
    "work": 1700,
    "quality": 29700,
    "durability": 60,
    "tag": "시간제 2",
    "group": "시간제 2",
    "category": "시간제"
  },
  {
    "region": "paenna",
    "missionId": 574,
    "missionName": "EX+: 임시 저장소 건설 지원",
    "job": "CRP",
    "rlvl": 751,
    "work": 7400,
    "quality": 19400,
    "durability": 70,
    "tag": "시간제 2",
    "group": "시간제 2",
    "category": "시간제"
  },
  {
    "region": "paenna",
    "missionId": 575,
    "missionName": "EX+: 고성능 침구 제작",
    "job": "CRP",
    "rlvl": 751,
    "work": 7200,
    "quality": 24100,
    "durability": 80,
    "tag": "날씨제 2",
    "group": "날씨제 2",
    "category": "날씨제"
  },
  {
    "region": "paenna",
    "missionId": 578,
    "missionName": "EX: 의회 전달용 공예품 제작",
    "job": "CRP",
    "rlvl": 721,
    "work": 2200,
    "quality": 14000,
    "durability": 25,
    "tag": "A-EX 2",
    "group": "A-EX 2",
    "category": "A-EX"
  },
  {
    "region": "paenna",
    "missionId": 579,
    "missionName": "EX: 의회 전달용 공예품 제작 2",
    "job": "CRP",
    "rlvl": 721,
    "work": 7600,
    "quality": 13600,
    "durability": 60,
    "tag": "A-EX 2 - 2",
    "group": "A-EX 2",
    "category": "A-EX"
  },
  {
    "region": "paenna",
    "missionId": 580,
    "missionName": "EX: 의회 전달용 공예품 제작 3",
    "job": "CRP",
    "rlvl": 722,
    "work": 600,
    "quality": 21100,
    "durability": 60,
    "tag": "A-EX 2 - 3",
    "group": "A-EX 2",
    "category": "A-EX"
  },
  {
    "region": "paenna",
    "missionId": 581,
    "missionName": "거주구 환경 개선 계획",
    "job": "CRP",
    "rlvl": 701,
    "work": 5100,
    "quality": 9500,
    "durability": 75,
    "tag": "시간제 1",
    "group": "시간제 1",
    "category": "시간제"
  },
  {
    "region": "paenna",
    "missionId": 582,
    "missionName": "EX: 거주구 환경 개선 계획 2",
    "job": "CRP",
    "rlvl": 723,
    "work": 4200,
    "quality": 14600,
    "durability": 65,
    "tag": "시간제 1 - 2",
    "group": "시간제 1",
    "category": "시간제"
  },
  {
    "region": "paenna",
    "missionId": 583,
    "missionName": "EX+: 거주구 환경 개선 계획 3",
    "job": "CRP",
    "rlvl": 751,
    "work": 5000,
    "quality": 18500,
    "durability": 25,
    "tag": "시간제 1 - 3",
    "group": "시간제 1",
    "category": "시간제"
  },
  {
    "region": "paenna",
    "missionId": 584,
    "missionName": "EX+: 수지 결정 정제 검증",
    "job": "CRP",
    "rlvl": 753,
    "work": 7000,
    "quality": 19500,
    "durability": 30,
    "tag": "시간제 3",
    "group": "시간제 3",
    "category": "시간제"
  },
  {
    "region": "paenna",
    "missionId": 584,
    "missionName": "EX+: 수지 결정 정제 검증",
    "job": "CRP",
    "rlvl": 753,
    "work": 10200,
    "quality": 27900,
    "durability": 55,
    "tag": "시간제 3",
    "group": "시간제 3",
    "category": "시간제"
  },
  {
    "region": "paenna",
    "missionId": 585,
    "missionName": "EX+: 수지 결정 정제 검증 2",
    "job": "CRP",
    "rlvl": 754,
    "work": 6500,
    "quality": 19200,
    "durability": 35,
    "tag": "시간제 3 - 2",
    "group": "시간제 3",
    "category": "시간제"
  },
  {
    "region": "paenna",
    "missionId": 585,
    "missionName": "EX+: 수지 결정 정제 검증 2",
    "job": "CRP",
    "rlvl": 754,
    "work": 9500,
    "quality": 27600,
    "durability": 60,
    "tag": "시간제 3 - 2",
    "group": "시간제 3",
    "category": "시간제"
  },
  {
    "region": "paenna",
    "missionId": 586,
    "missionName": "EX+: 수지 결정 정제 검증 3",
    "job": "CRP",
    "rlvl": 755,
    "work": 8900,
    "quality": 23000,
    "durability": 40,
    "tag": "시간제 3 - 3",
    "group": "시간제 3",
    "category": "시간제"
  },
  {
    "region": "paenna",
    "missionId": 586,
    "missionName": "EX+: 수지 결정 정제 검증 3",
    "job": "CRP",
    "rlvl": 755,
    "work": 12000,
    "quality": 32300,
    "durability": 65,
    "tag": "시간제 3 - 3",
    "group": "시간제 3",
    "category": "시간제"
  }
];
