{
    "region": "auxesia",
    "missionId": 1389,
    "missionName": "EX: 탐색 도구 환경 대응",
    "job": "CRP",
    "rlvl": 727,
    "work": 2300,
    "quality": 24700,
    "durability": 70,
    "tag": "A-EX 3",
    "group": "A-EX 3",
    "category": "A-EX"
  },
  {
    "region": "auxesia",
    "missionId": 1390,
    "missionName": "EX: 상급 반출 자재 조달",
    "job": "CRP",
    "rlvl": 728,
    "work": 9700,
    "quality": 17300,
    "durability": 70,
    "tag": "A-EX 2",
    "group": "A-EX 2",
    "category": "A-EX"
  },
  {
    "region": "auxesia",
    "missionId": 1391,
    "missionName": "EX: 아욱세시아용 연료 재료 개발",
    "job": "CRP",
    "rlvl": 729,
    "work": 8500,
    "quality": 19500,
    "durability": 60,
    "tag": "A-EX",
    "group": "A-EX",
    "category": "A-EX"
  },
  {
    "region": "auxesia",
    "missionId": 1393,
    "missionName": "EX+: 고순도 바이오 연료 개발",
    "job": "CRP",
    "rlvl": 772,
    "work": 7700,
    "quality": 26000,
    "durability": 50,
    "tag": "A-EX+ 2",
    "group": "A-EX+ 2",
    "category": "A-EX+"
  },
  {
    "region": "auxesia",
    "missionId": 1395,
    "missionName": "MASTER: 중장비 연료 개량",
    "job": "CRP",
    "rlvl": 773,
    "work": 7800,
    "quality": 25100,
    "durability": 60,
    "tag": "A-MASTER",
    "group": "A-MASTER",
    "category": "A-MASTER"
  },
  {
    "region": "auxesia",
    "missionId": 1396,
    "missionName": "MASTER: 특제 연금 구체 개발",
    "job": "CRP",
    "rlvl": 774,
    "work": 6900,
    "quality": 22100,
    "durability": 45,
    "tag": "A-MASTER 2",
    "group": "A-MASTER 2",
    "category": "A-MASTER"
  },
  {
    "region": "auxesia",
    "missionId": 1397,
    "missionName": "MASTER: 재생 에너지 연료 탐구",
    "job": "CRP",
    "rlvl": 775,
    "work": 7400,
    "quality": 26300,
    "durability": 80,
    "tag": "A-MASTER 3",
    "group": "A-MASTER 3",
    "category": "A-MASTER"
  },
  {
    "region": "auxesia",
    "missionId": 1417,
    "missionName": "EX: 탐색용 상급 자재 지원",
    "job": "BSM",
    "rlvl": 727,
    "work": 2300,
    "quality": 24700,
    "durability": 70,
    "tag": "A-EX 3",
    "group": "A-EX 3",
    "category": "A-EX"
  },
  {
    "region": "auxesia",
    "missionId": 1418,
    "missionName": "EX: 고강도 철사 조달",
    "job": "BSM",
    "rlvl": 728,
    "work": 9700,
    "quality": 17300,
    "durability": 70,
    "tag": "A-EX 2",
    "group": "A-EX 2",
    "category": "A-EX"
  },
  {
    "region": "auxesia",
    "missionId": 1419,
    "missionName": "EX: 환경 유지 비품 개발 지원",
    "job": "BSM",
    "rlvl": 729,
    "work": 8500,
    "quality": 19500,
    "durability": 60,
    "tag": "A-EX",
    "group": "A-EX",
    "category": "A-EX"
  },
  {
    "region": "auxesia",
    "missionId": 1421,
    "missionName": "EX+: 에테르 관측 기기 지속 개발",
    "job": "BSM",
    "rlvl": 772,
    "work": 7700,
    "quality": 26000,
    "durability": 50,
    "tag": "A-EX+ 2",
    "group": "A-EX+ 2",
    "category": "A-EX+"
  },
  {
    "region": "auxesia",
    "missionId": 1423,
    "missionName": "MASTER: 굴착 드릴 개량 작업",
    "job": "BSM",
    "rlvl": 773,
    "work": 7800,
    "quality": 25100,
    "durability": 60,
    "tag": "A-MASTER",
    "group": "A-MASTER",
    "category": "A-MASTER"
  },
  {
    "region": "auxesia",
    "missionId": 1424,
    "missionName": "MASTER: 유적 복원 자재 제작",
    "job": "BSM",
    "rlvl": 774,
    "work": 6900,
    "quality": 22100,
    "durability": 45,
    "tag": "A-MASTER 2",
    "group": "A-MASTER 2",
    "category": "A-MASTER"
  },
  {
    "region": "auxesia",
    "missionId": 1425,
    "missionName": "MASTER: 중추 기구 구조 견본 제작",
    "job": "BSM",
    "rlvl": 775,
    "work": 7400,
    "quality": 26300,
    "durability": 80,
    "tag": "A-MASTER 3",
    "group": "A-MASTER 3",
    "category": "A-MASTER"
  },
  {
    "region": "auxesia",
    "missionId": 1445,
    "missionName": "EX: 탐색용 상급 자재 지원",
    "job": "ARM",
    "rlvl": 727,
    "work": 2300,
    "quality": 24700,
    "durability": 70,
    "tag": "A-EX 3",
    "group": "A-EX 3",
    "category": "A-EX"
  },
  {
    "region": "auxesia",
    "missionId": 1446,
    "missionName": "EX: 고강도 철사 조달",
    "job": "ARM",
    "rlvl": 728,
    "work": 9700,
    "quality": 17300,
    "durability": 70,
    "tag": "A-EX 2",
    "group": "A-EX 2",
    "category": "A-EX"
  },
  {
    "region": "auxesia",
    "missionId": 1447,
    "missionName": "EX: 환경 유지 비품 개발 지원",
    "job": "ARM",
    "rlvl": 729,
    "work": 8500,
    "quality": 19500,
    "durability": 60,
    "tag": "A-EX",
    "group": "A-EX",
    "category": "A-EX"
  },
  {
    "region": "auxesia",
    "missionId": 1449,
    "missionName": "EX+: 에테르 관측 기기 지속 개발",
    "job": "ARM",
    "rlvl": 772,
    "work": 7700,
    "quality": 26000,
    "durability": 50,
    "tag": "A-EX+ 2",
    "group": "A-EX+ 2",
    "category": "A-EX+"
  },
  {
    "region": "auxesia",
    "missionId": 1451,
    "missionName": "MASTER: 촉진제 분사기 개량 작업",
    "job": "ARM",
    "rlvl": 773,
    "work": 7800,
    "quality": 25100,
    "durability": 60,
    "tag": "A-MASTER",
    "group": "A-MASTER",
    "category": "A-MASTER"
  },
  {
    "region": "auxesia",
    "missionId": 1452,
    "missionName": "MASTER: 유적 복원 자재 제작",
    "job": "ARM",
    "rlvl": 774,
    "work": 6900,
    "quality": 22100,
    "durability": 45,
    "tag": "A-MASTER 2",
    "group": "A-MASTER 2",
    "category": "A-MASTER"
  },
  {
    "region": "auxesia",
    "missionId": 1453,
    "missionName": "MASTER: 선구자 단말 재현 작업",
    "job": "ARM",
    "rlvl": 775,
    "work": 7400,
    "quality": 26300,
    "durability": 80,
    "tag": "A-MASTER 3",
    "group": "A-MASTER 3",
    "category": "A-MASTER"
  },
  {
    "region": "auxesia",
    "missionId": 1473,
    "missionName": "EX: 탐색용 상급 자재 지원",
    "job": "GSM",
    "rlvl": 727,
    "work": 2300,
    "quality": 24700,
    "durability": 70,
    "tag": "A-EX 3",
    "group": "A-EX 3",
    "category": "A-EX"
  },
  {
    "region": "auxesia",
    "missionId": 1474,
    "missionName": "EX: 고강도 철사 조달",
    "job": "GSM",
    "rlvl": 728,
    "work": 9700,
    "quality": 17300,
    "durability": 70,
    "tag": "A-EX 2",
    "group": "A-EX 2",
    "category": "A-EX"
  },
  {
    "region": "auxesia",
    "missionId": 1475,
    "missionName": "EX: 환경 유지 비품 개발 지원",
    "job": "GSM",
    "rlvl": 729,
    "work": 8500,
    "quality": 19500,
    "durability": 60,
    "tag": "A-EX",
    "group": "A-EX",
    "category": "A-EX"
  },
  {
    "region": "auxesia",
    "missionId": 1477,
    "missionName": "EX+: 에테르 관측 기기 지속 개발",
    "job": "GSM",
    "rlvl": 772,
    "work": 7700,
    "quality": 26000,
    "durability": 50,
    "tag": "A-EX+ 2",
    "group": "A-EX+ 2",
    "category": "A-EX+"
  },
  {
    "region": "auxesia",
    "missionId": 1479,
    "missionName": "MASTER: 용접기 개량 작업",
    "job": "GSM",
    "rlvl": 773,
    "work": 7800,
    "quality": 25100,
    "durability": 60,
    "tag": "A-MASTER",
    "group": "A-MASTER",
    "category": "A-MASTER"
  },
  {
    "region": "auxesia",
    "missionId": 1480,
    "missionName": "MASTER: 유적 복원 자재 제작",
    "job": "GSM",
    "rlvl": 774,
    "work": 6900,
    "quality": 22100,
    "durability": 45,
    "tag": "A-MASTER 2",
    "group": "A-MASTER 2",
    "category": "A-MASTER"
  },
  {
    "region": "auxesia",
    "missionId": 1481,
    "missionName": "MASTER: 선구자 화면 장치 재현 작업",
    "job": "GSM",
    "rlvl": 775,
    "work": 7400,
    "quality": 26300,
    "durability": 80,
    "tag": "A-MASTER 3",
    "group": "A-MASTER 3",
    "category": "A-MASTER"
  },
  {
    "region": "auxesia",
    "missionId": 1501,
    "missionName": "EX: 탐색 도구 환경 대응",
    "job": "LTW",
    "rlvl": 727,
    "work": 2300,
    "quality": 24700,
    "durability": 70,
    "tag": "A-EX 3",
    "group": "A-EX 3",
    "category": "A-EX"
  },
  {
    "region": "auxesia",
    "missionId": 1502,
    "missionName": "EX: 상급 반출 자재 조달",
    "job": "LTW",
    "rlvl": 728,
    "work": 9700,
    "quality": 17300,
    "durability": 70,
    "tag": "A-EX 2",
    "group": "A-EX 2",
    "category": "A-EX"
  },
  {
    "region": "auxesia",
    "missionId": 1503,
    "missionName": "EX: 아욱세시아용 연료 재료 개발",
    "job": "LTW",
    "rlvl": 729,
    "work": 8500,
    "quality": 19500,
    "durability": 60,
    "tag": "A-EX",
    "group": "A-EX",
    "category": "A-EX"
  },
  {
    "region": "auxesia",
    "missionId": 1505,
    "missionName": "EX+: 정비복 제작",
    "job": "LTW",
    "rlvl": 772,
    "work": 7700,
    "quality": 26000,
    "durability": 50,
    "tag": "A-EX+ 2",
    "group": "A-EX+ 2",
    "category": "A-EX+"
  },
  {
    "region": "auxesia",
    "missionId": 1507,
    "missionName": "MASTER: 우주복 개량 제작",
    "job": "LTW",
    "rlvl": 773,
    "work": 7800,
    "quality": 25100,
    "durability": 60,
    "tag": "A-MASTER",
    "group": "A-MASTER",
    "category": "A-MASTER"
  },
  {
    "region": "auxesia",
    "missionId": 1508,
    "missionName": "MASTER: 조종복 개량 제작",
    "job": "LTW",
    "rlvl": 774,
    "work": 6900,
    "quality": 22100,
    "durability": 45,
    "tag": "A-MASTER 2",
    "group": "A-MASTER 2",
    "category": "A-MASTER"
  },
  {
    "region": "auxesia",
    "missionId": 1509,
    "missionName": "MASTER: 강화 우주복 정밀 부재 제작",
    "job": "LTW",
    "rlvl": 775,
    "work": 7400,
    "quality": 26300,
    "durability": 80,
    "tag": "A-MASTER 3",
    "group": "A-MASTER 3",
    "category": "A-MASTER"
  },
  {
    "region": "auxesia",
    "missionId": 1529,
    "missionName": "EX: 탐색 도구 환경 대응",
    "job": "WVR",
    "rlvl": 727,
    "work": 2300,
    "quality": 24700,
    "durability": 70,
    "tag": "A-EX 3",
    "group": "A-EX 3",
    "category": "A-EX"
  },
  {
    "region": "auxesia",
    "missionId": 1530,
    "missionName": "EX: 상급 반출 자재 조달",
    "job": "WVR",
    "rlvl": 728,
    "work": 9700,
    "quality": 17300,
    "durability": 70,
    "tag": "A-EX 2",
    "group": "A-EX 2",
    "category": "A-EX"
  },
  {
    "region": "auxesia",
    "missionId": 1531,
    "missionName": "EX: 아욱세시아용 연료 재료 개발",
    "job": "WVR",
    "rlvl": 729,
    "work": 8500,
    "quality": 19500,
    "durability": 60,
    "tag": "A-EX",
    "group": "A-EX",
    "category": "A-EX"
  },
  {
    "region": "auxesia",
    "missionId": 1533,
    "missionName": "EX+: 탐험복 제작",
    "job": "WVR",
    "rlvl": 772,
    "work": 7700,
    "quality": 26000,
    "durability": 50,
    "tag": "A-EX+ 2",
    "group": "A-EX+ 2",
    "category": "A-EX+"
  },
  {
    "region": "auxesia",
    "missionId": 1535,
    "missionName": "MASTER: 승무원복 개량 제작",
    "job": "WVR",
    "rlvl": 773,
    "work": 7800,
    "quality": 25100,
    "durability": 60,
    "tag": "A-MASTER",
    "group": "A-MASTER",
    "category": "A-MASTER"
  },
  {
    "region": "auxesia",
    "missionId": 1536,
    "missionName": "MASTER: 선장복 개량 제작",
    "job": "WVR",
    "rlvl": 774,
    "work": 6900,
    "quality": 22100,
    "durability": 45,
    "tag": "A-MASTER 2",
    "group": "A-MASTER 2",
    "category": "A-MASTER"
  },
  {
    "region": "auxesia",
    "missionId": 1537,
    "missionName": "MASTER: 제독 의상 장식 부재 제작",
    "job": "WVR",
    "rlvl": 775,
    "work": 7400,
    "quality": 26300,
    "durability": 80,
    "tag": "A-MASTER 3",
    "group": "A-MASTER 3",
    "category": "A-MASTER"
  },
  {
    "region": "auxesia",
    "missionId": 1557,
    "missionName": "EX: 행성 식물 추출 응용",
    "job": "ALC",
    "rlvl": 727,
    "work": 2300,
    "quality": 24700,
    "durability": 70,
    "tag": "A-EX 3",
    "group": "A-EX 3",
    "category": "A-EX"
  },
  {
    "region": "auxesia",
    "missionId": 1558,
    "missionName": "EX: 소비 건축재 개발 지원",
    "job": "ALC",
    "rlvl": 728,
    "work": 9700,
    "quality": 17300,
    "durability": 70,
    "tag": "A-EX 2",
    "group": "A-EX 2",
    "category": "A-EX"
  },
  {
    "region": "auxesia",
    "missionId": 1559,
    "missionName": "EX: 위문용 고급술 양조",
    "job": "ALC",
    "rlvl": 729,
    "work": 8500,
    "quality": 19500,
    "durability": 60,
    "tag": "A-EX",
    "group": "A-EX",
    "category": "A-EX"
  },
  {
    "region": "auxesia",
    "missionId": 1561,
    "missionName": "EX+: 지속성 자원 개발 지원",
    "job": "ALC",
    "rlvl": 772,
    "work": 7700,
    "quality": 26000,
    "durability": 50,
    "tag": "A-EX+ 2",
    "group": "A-EX+ 2",
    "category": "A-EX+"
  },
  {
    "region": "auxesia",
    "missionId": 1563,
    "missionName": "MASTER: 유적용 연금제 고도 개발",
    "job": "ALC",
    "rlvl": 773,
    "work": 7800,
    "quality": 25100,
    "durability": 60,
    "tag": "A-MASTER",
    "group": "A-MASTER",
    "category": "A-MASTER"
  },
  {
    "region": "auxesia",
    "missionId": 1564,
    "missionName": "MASTER: 고도 복원용 자재 지원",
    "job": "ALC",
    "rlvl": 774,
    "work": 6900,
    "quality": 22100,
    "durability": 45,
    "tag": "A-MASTER 2",
    "group": "A-MASTER 2",
    "category": "A-MASTER"
  },
  {
    "region": "auxesia",
    "missionId": 1565,
    "missionName": "MASTER: 우주 도구 강화 지원",
    "job": "ALC",
    "rlvl": 775,
    "work": 7400,
    "quality": 26300,
    "durability": 80,
    "tag": "A-MASTER 3",
    "group": "A-MASTER 3",
    "category": "A-MASTER"
  },
  {
    "region": "auxesia",
    "missionId": 1585,
    "missionName": "EX: 행성 식물 추출 응용",
    "job": "CUL",
    "rlvl": 727,
    "work": 2300,
    "quality": 24700,
    "durability": 70,
    "tag": "A-EX 3",
    "group": "A-EX 3",
    "category": "A-EX"
  },
  {
    "region": "auxesia",
    "missionId": 1586,
    "missionName": "EX: 소비 건축재 개발 지원",
    "job": "CUL",
    "rlvl": 728,
    "work": 9700,
    "quality": 17300,
    "durability": 70,
    "tag": "A-EX 2",
    "group": "A-EX 2",
    "category": "A-EX"
  },
  {
    "region": "auxesia",
    "missionId": 1587,
    "missionName": "EX: 위문용 고급술 양조",
    "job": "CUL",
    "rlvl": 729,
    "work": 8500,
    "quality": 19500,
    "durability": 60,
    "tag": "A-EX",
    "group": "A-EX",
    "category": "A-EX"
  },
  {
    "region": "auxesia",
    "missionId": 1589,
    "missionName": "EX+: 지속성 자원 개발 지원",
    "job": "CUL",
    "rlvl": 772,
    "work": 7700,
    "quality": 26000,
    "durability": 50,
    "tag": "A-EX+ 2",
    "group": "A-EX+ 2",
    "category": "A-EX+"
  },
  {
    "region": "auxesia",
    "missionId": 1591,
    "missionName": "MASTER: 우주 완전식 탐구",
    "job": "CUL",
    "rlvl": 773,
    "work": 7800,
    "quality": 25100,
    "durability": 60,
    "tag": "A-MASTER",
    "group": "A-MASTER",
    "category": "A-MASTER"
  },
  {
    "region": "auxesia",
    "missionId": 1592,
    "missionName": "MASTER: 행성 식물 식용 연구",
    "job": "CUL",
    "rlvl": 774,
    "work": 6900,
    "quality": 22100,
    "durability": 45,
    "tag": "A-MASTER 2",
    "group": "A-MASTER 2",
    "category": "A-MASTER"
  },
  {
    "region": "auxesia",
    "missionId": 1593,
    "missionName": "MASTER: 우주 도구 개량 지원",
    "job": "CUL",
    "rlvl": 775,
    "work": 7400,
    "quality": 26300,
    "durability": 80,
    "tag": "A-MASTER 3",
    "group": "A-MASTER 3",
    "category": "A-MASTER"
  }
];
