const RECIPES_AUXESIA = [
  {
    "region": "auxesia",
    "missionId": 1389,
    "missionName": "EX: 탐색 도구 환경 대응",
    "job": "CRP",
    "rlvl": 727,
    "work": 2300,
    "quality": 24700,
    "durability": 70,
    "tag": "A-EX 3",
    "group": "A-EX 3",
    "category": "A-EX",
    "isSub": false
  },
  {
    "region": "auxesia",
    "missionId": 1390,
    "missionName": "EX: 상급 반출 자재 조달",
    "job": "CRP",
    "rlvl": 728,
    "work": 9700,
    "quality": 17300,
    "durability": 70,
    "tag": "A-EX 2",
    "group": "A-EX 2",
    "category": "A-EX",
    "isSub": false
  },
  {
    "region": "auxesia",
    "missionId": 1391,
    "missionName": "EX: 아욱세시아용 연료 재료 개발",
    "job": "CRP",
    "rlvl": 729,
    "work": 8500,
    "quality": 19500,
    "durability": 60,
    "tag": "A-EX",
    "group": "A-EX",
    "category": "A-EX",
    "isSub": false
  },
  {
    "region": "auxesia",
    "missionId": 1393,
    "missionName": "EX+: 고순도 바이오 연료 개발",
    "job": "CRP",
    "rlvl": 772,
    "work": 7700,
    "quality": 26000,
    "durability": 50,
    "tag": "A-EX+ 2",
    "group": "A-EX+ 2",
    "category": "A-EX+",
    "isSub": false
  },
  {
    "region": "auxesia",
    "missionId": 1395,
    "missionName": "MASTER: 중장비 연료 개량",
    "job": "CRP",
    "rlvl": 773,
    "work": 7800,
    "quality": 25100,
    "durability": 60,
    "tag": "A-MASTER",
    "group": "A-MASTER",
    "category": "A-MASTER",
    "isSub": false
  },
  {
    "region": "auxesia",
    "missionId": 1396,
    "missionName": "MASTER: 특제 연금 구체 개발",
    "job": "CRP",
    "rlvl": 774,
    "work": 6900,
    "quality": 22100,
    "durability": 45,
    "tag": "A-MASTER 2",
    "group": "A-MASTER 2",
    "category": "A-MASTER",
    "isSub": false
  },
  {
    "region": "auxesia",
    "missionId": 1397,
    "missionName": "MASTER: 재생 에너지 연료 탐구",
    "job": "CRP",
    "rlvl": 775,
    "work": 7400,
    "quality": 26300,
    "durability": 80,
    "tag": "A-MASTER 3",
    "group": "A-MASTER 3",
    "category": "A-MASTER",
    "isSub": false
  }
];
