const HARD_RECIPES = [
  {
    "region": "dongyeong",
    "missionId": 27,
    "missionName": "EX: 시험용 소재 최종 가공 검증",
    "job": "CRP",
    "rlvl": 721,
    "work": 7800,
    "quality": 14900,
    "durability": 65,
    "tag": "A-EX",
    "group": "A-EX",
    "category": "A-EX"
  },
  {
    "region": "dongyeong",
    "missionId": 28,
    "missionName": "EX: 배식용 쟁반 제작",
    "job": "CRP",
    "rlvl": 722,
    "work": 9000,
    "quality": 23000,
    "durability": 80,
    "tag": "A-EX 2",
    "group": "A-EX 2",
    "category": "A-EX"
  },
  {
    "region": "dongyeong",
    "missionId": 29,
    "missionName": "EX: 이층 침대 제작",
    "job": "CRP",
    "rlvl": 723,
    "work": 8700,
    "quality": 22000,
    "durability": 70,
    "tag": "A-EX 3",
    "group": "A-EX 3",
    "category": "A-EX"
  },
  {
    "region": "dongyeong",
    "missionId": 30,
    "missionName": "EX: 작업 보조 설비 제작",
    "job": "CRP",
    "rlvl": 724,
    "work": 10000,
    "quality": 12000,
    "durability": 55,
    "tag": "날씨제 1",
    "group": "날씨제 1",
    "category": "날씨제"
  },
  {
    "region": "dongyeong",
    "missionId": 30,
    "missionName": "EX: 작업 보조 설비 제작",
    "job": "CRP",
    "rlvl": 725,
    "work": 10000,
    "quality": 12000,
    "durability": 55,
    "tag": "날씨제 1 - 1",
    "group": "날씨제 1",
    "category": "날씨제"
  },
  {
    "region": "dongyeong",
    "missionId": 30,
    "missionName": "EX: 작업 보조 설비 제작",
    "job": "CRP",
    "rlvl": 726,
    "work": 10000,
    "quality": 12000,
    "durability": 55,
    "tag": "날씨제 1 - 2",
    "group": "날씨제 1",
    "category": "날씨제"
  },
  {
    "region": "dongyeong",
    "missionId": 31,
    "missionName": "EX+: 고품질 제작도구 보충",
    "job": "CRP",
    "rlvl": 742,
    "work": 4700,
    "quality": 14900,
    "durability": 20,
    "tag": "날씨제 2",
    "group": "날씨제 2",
    "category": "날씨제"
  },
  {
    "region": "dongyeong",
    "missionId": 31,
    "missionName": "EX+: 고품질 제작도구 보충",
    "job": "CRP",
    "rlvl": 743,
    "work": 9500,
    "quality": 24000,
    "durability": 60,
    "tag": "날씨제 2",
    "group": "날씨제 2",
    "category": "날씨제"
  },
  {
    "region": "dongyeong",
    "missionId": 32,
    "missionName": "EX+: 상부용 발판 제작",
    "job": "CRP",
    "rlvl": 742,
    "work": 4700,
    "quality": 14900,
    "durability": 20,
    "tag": "날씨제 3",
    "group": "날씨제 3",
    "category": "날씨제"
  },
  {
    "region": "dongyeong",
    "missionId": 32,
    "missionName": "EX+: 상부용 발판 제작",
    "job": "CRP",
    "rlvl": 744,
    "work": 9300,
    "quality": 22500,
    "durability": 60,
    "tag": "날씨제 3",
    "group": "날씨제 3",
    "category": "날씨제"
  },
  {
    "region": "dongyeong",
    "missionId": 33,
    "missionName": "동력 전달용 샤프트 제작",
    "job": "CRP",
    "rlvl": 701,
    "work": 6600,
    "quality": 12300,
    "durability": 40,
    "tag": "A - 2",
    "group": "A-2",
    "category": "A"
  },
  {
    "region": "dongyeong",
    "missionId": 34,
    "missionName": "EX: 동력 전달용 샤프트 제작 2",
    "job": "CRP",
    "rlvl": 721,
    "work": 7500,
    "quality": 15400,
    "durability": 75,
    "tag": "A - 2 - 2",
    "group": "A-2",
    "category": "A"
  },
  {
    "region": "dongyeong",
    "missionId": 35,
    "missionName": "성질 특화 소재 조달",
    "job": "CRP",
    "rlvl": 701,
    "work": 2500,
    "quality": 11300,
    "durability": 20,
    "tag": "A - 1",
    "group": "A-1",
    "category": "A"
  },
  {
    "region": "dongyeong",
    "missionId": 36,
    "missionName": "EX: 성질 특화 소재 조달 2",
    "job": "CRP",
    "rlvl": 721,
    "work": 19800,
    "quality": 1100,
    "durability": 25,
    "tag": "A - 1- 2",
    "group": "A-1",
    "category": "A"
  },
  {
    "region": "dongyeong",
    "missionId": 37,
    "missionName": "EX+: 연구용 대형 수조 제작",
    "job": "CRP",
    "rlvl": 741,
    "work": 9600,
    "quality": 17400,
    "durability": 80,
    "tag": "A - 1 - 3",
    "group": "A-1",
    "category": "A"
  },
  {
    "region": "dongyeong",
    "missionId": 38,
    "missionName": "EX: 휴식 시설용 소재 제작",
    "job": "CRP",
    "rlvl": 721,
    "work": 9100,
    "quality": 16300,
    "durability": 35,
    "tag": "A-EX 4",
    "group": "A-EX 4",
    "category": "A-EX"
  },
  {
    "region": "dongyeong",
    "missionId": 39,
    "missionName": "EX+: 휴식 시설용 가구 제작",
    "job": "CRP",
    "rlvl": 741,
    "work": 10600,
    "quality": 17100,
    "durability": 50,
    "tag": "A-EX 4 - 2",
    "group": "A-EX 4",
    "category": "A-EX"
  },
  {
    "region": "dongyeong",
    "missionId": 40,
    "missionName": "화물 포장 소재 제작",
    "job": "CRP",
    "rlvl": 701,
    "work": 5000,
    "quality": 14100,
    "durability": 35,
    "tag": "시간제 1",
    "group": "시간제 1",
    "category": "시간제"
  },
  {
    "region": "dongyeong",
    "missionId": 41,
    "missionName": "EX: 화물 포장 소재 제작 2",
    "job": "CRP",
    "rlvl": 721,
    "work": 1200,
    "quality": 19000,
    "durability": 55,
    "tag": "시간제 1 - 2",
    "group": "시간제 1",
    "category": "시간제"
  },
  {
    "region": "dongyeong",
    "missionId": 42,
    "missionName": "EX+: 탐사차용 화물 포장재 제작",
    "job": "CRP",
    "rlvl": 741,
    "work": 1500,
    "quality": 23200,
    "durability": 75,
    "tag": "시간제 1 - 3",
    "group": "시간제 1",
    "category": "시간제"
  },
  {
    "region": "dongyeong",
    "missionId": 43,
    "missionName": "EX+: 생물연료 제작",
    "job": "CRP",
    "rlvl": 746,
    "work": 7300,
    "quality": 18900,
    "durability": 30,
    "tag": "시간제 2",
    "group": "시간제 2",
    "category": "시간제"
  },
  {
    "region": "dongyeong",
    "missionId": 43,
    "missionName": "EX+: 생물연료 제작",
    "job": "CRP",
    "rlvl": 746,
    "work": 10000,
    "quality": 27400,
    "durability": 55,
    "tag": "시간제 2",
    "group": "시간제 2",
    "category": "시간제"
  },
  {
    "region": "dongyeong",
    "missionId": 44,
    "missionName": "EX+: 생물연료 제작 2",
    "job": "CRP",
    "rlvl": 747,
    "work": 6500,
    "quality": 18000,
    "durability": 35,
    "tag": "시간제 2 - 2",
    "group": "시간제 2",
    "category": "시간제"
  },
  {
    "region": "dongyeong",
    "missionId": 44,
    "missionName": "EX+: 생물연료 제작 2",
    "job": "CRP",
    "rlvl": 747,
    "work": 9500,
    "quality": 26800,
    "durability": 60,
    "tag": "시간제 2 - 2",
    "group": "시간제 2",
    "category": "시간제"
  },
  {
    "region": "dongyeong",
    "missionId": 45,
    "missionName": "EX+: 생물연료 제작 최종 공정",
    "job": "CRP",
    "rlvl": 748,
    "work": 8500,
    "quality": 19500,
    "durability": 40,
    "tag": "시간제 2 - 3",
    "group": "시간제 2",
    "category": "시간제"
  },
  {
    "region": "dongyeong",
    "missionId": 45,
    "missionName": "EX+: 생물연료 제작 최종 공정",
    "job": "CRP",
    "rlvl": 748,
    "work": 11400,
    "quality": 29800,
    "durability": 70,
    "tag": "시간제 2 -3",
    "group": "시간제 2",
    "category": "시간제"
  },
  {
    "region": "dongyeong",
    "missionId": 496,
    "missionName": "EX: 수산물 연구용 물자함 증산",
    "job": "CRP",
    "rlvl": 721,
    "work": 7500,
    "quality": 15400,
    "durability": 75,
    "tag": "광부 + 목수",
    "group": "광부 + 목수",
    "category": "기타"
  },
  {
    "region": "dongyeong",
    "missionId": 505,
    "missionName": "EX+: 월면 소재 채집 도구 이용",
    "job": "CRP",
    "rlvl": 741,
    "work": 9600,
    "quality": 17400,
    "durability": 80,
    "tag": "날씨제 어부 + 목수",
    "group": "날씨제 어부 + 목수",
    "category": "날씨제"
  },
  {
    "region": "paenna",
    "missionId": 571,
    "missionName": "EX: 야외 활동용 비품 제작",
    "job": "CRP",
    "rlvl": 721,
    "work": 7800,
    "quality": 12200,
    "durability": 65,
    "tag": "A-EX",
    "group": "A-EX",
    "category": "A-EX"
  },
  {
    "region": "paenna",
    "missionId": 572,
    "missionName": "EX: 고성능 장인 도구 조달",
    "job": "CRP",
    "rlvl": 724,
    "work": 9700,
    "quality": 11600,
    "durability": 55,
    "tag": "A-EX 3",
    "group": "A-EX 3",
    "category": "A-EX"
  },
  {
    "region": "paenna",
    "missionId": 572,
    "missionName": "EX: 고성능 장인 도구 조달",
    "job": "CRP",
    "rlvl": 725,
    "work": 9700,
    "quality": 11600,
    "durability": 55,
    "tag": "A-EX 3 - 2",
    "group": "A-EX 3",
    "category": "A-EX"
  },
  {
    "region": "paenna",
    "missionId": 572,
    "missionName": "EX: 고성능 장인 도구 조달",
    "job": "CRP",
    "rlvl": 726,
    "work": 9700,
    "quality": 11600,
    "durability": 55,
    "tag": "A-EX 3 - 3",
    "group": "A-EX 3",
    "category": "A-EX"
  },
  {
    "region": "paenna",
    "missionId": 573,
    "missionName": "EX: 우주 운송용 포장재 제작",
    "job": "CRP",
    "rlvl": 721,
    "work": 5000,
    "quality": 12400,
    "durability": 35,
    "tag": "날씨제 1",
    "group": "날씨제 1",
    "category": "날씨제"
  },
  {
    "region": "paenna",
    "missionId": 573,
    "missionName": "EX: 우주 운송용 포장재 제작",
    "job": "CRP",
    "rlvl": 721,
    "work": 8700,
    "quality": 18000,
    "durability": 70,
    "tag": "날씨제 1",
    "group": "날씨제 1",
    "category": "날씨제"
  },
  {
    "region": "paenna",
    "missionId": 574,
    "missionName": "EX+: 임시 저장소 건설 지원",
    "job": "CRP",
    "rlvl": 742,
    "work": 1700,
    "quality": 29700,
    "durability": 60,
    "tag": "시간제 2",
    "group": "시간제 2",
    "category": "시간제"
  },
  {
    "region": "paenna",
    "missionId": 574,
    "missionName": "EX+: 임시 저장소 건설 지원",
    "job": "CRP",
    "rlvl": 751,
    "work": 7400,
    "quality": 19400,
    "durability": 70,
    "tag": "시간제 2",
    "group": "시간제 2",
    "category": "시간제"
  },
  {
    "region": "paenna",
    "missionId": 575,
    "missionName": "EX+: 고성능 침구 제작",
    "job": "CRP",
    "rlvl": 751,
    "work": 7200,
    "quality": 24100,
    "durability": 80,
    "tag": "날씨제 2",
    "group": "날씨제 2",
    "category": "날씨제"
  },
  {
    "region": "paenna",
    "missionId": 578,
    "missionName": "EX: 의회 전달용 공예품 제작",
    "job": "CRP",
    "rlvl": 721,
    "work": 2200,
    "quality": 14000,
    "durability": 25,
    "tag": "A-EX 2",
    "group": "A-EX 2",
    "category": "A-EX"
  },
  {
    "region": "paenna",
    "missionId": 579,
    "missionName": "EX: 의회 전달용 공예품 제작 2",
    "job": "CRP",
    "rlvl": 721,
    "work": 7600,
    "quality": 13600,
    "durability": 60,
    "tag": "A-EX 2 - 2",
    "group": "A-EX 2",
    "category": "A-EX"
  },
  {
    "region": "paenna",
    "missionId": 580,
    "missionName": "EX: 의회 전달용 공예품 제작 3",
    "job": "CRP",
    "rlvl": 722,
    "work": 600,
    "quality": 21100,
    "durability": 60,
    "tag": "A-EX 2 - 3",
    "group": "A-EX 2",
    "category": "A-EX"
  },
  {
    "region": "paenna",
    "missionId": 581,
    "missionName": "거주구 환경 개선 계획",
    "job": "CRP",
    "rlvl": 701,
    "work": 5100,
    "quality": 9500,
    "durability": 75,
    "tag": "시간제 1",
    "group": "시간제 1",
    "category": "시간제"
  },
  {
    "region": "paenna",
    "missionId": 582,
    "missionName": "EX: 거주구 환경 개선 계획 2",
    "job": "CRP",
    "rlvl": 723,
    "work": 4200,
    "quality": 14600,
    "durability": 65,
    "tag": "시간제 1 - 2",
    "group": "시간제 1",
    "category": "시간제"
  },
  {
    "region": "paenna",
    "missionId": 583,
    "missionName": "EX+: 거주구 환경 개선 계획 3",
    "job": "CRP",
    "rlvl": 751,
    "work": 5000,
    "quality": 18500,
    "durability": 25,
    "tag": "시간제 1 - 3",
    "group": "시간제 1",
    "category": "시간제"
  },
  {
    "region": "paenna",
    "missionId": 584,
    "missionName": "EX+: 수지 결정 정제 검증",
    "job": "CRP",
    "rlvl": 753,
    "work": 7000,
    "quality": 19500,
    "durability": 30,
    "tag": "시간제 3",
    "group": "시간제 3",
    "category": "시간제"
  },
  {
    "region": "paenna",
    "missionId": 584,
    "missionName": "EX+: 수지 결정 정제 검증",
    "job": "CRP",
    "rlvl": 753,
    "work": 10200,
    "quality": 27900,
    "durability": 55,
    "tag": "시간제 3",
    "group": "시간제 3",
    "category": "시간제"
  },
  {
    "region": "paenna",
    "missionId": 585,
    "missionName": "EX+: 수지 결정 정제 검증 2",
    "job": "CRP",
    "rlvl": 754,
    "work": 6500,
    "quality": 19200,
    "durability": 35,
    "tag": "시간제 3 - 2",
    "group": "시간제 3",
    "category": "시간제"
  },
  {
    "region": "paenna",
    "missionId": 585,
    "missionName": "EX+: 수지 결정 정제 검증 2",
    "job": "CRP",
    "rlvl": 754,
    "work": 9500,
    "quality": 27600,
    "durability": 60,
    "tag": "시간제 3 - 2",
    "group": "시간제 3",
    "category": "시간제"
  },
  {
    "region": "paenna",
    "missionId": 586,
    "missionName": "EX+: 수지 결정 정제 검증 3",
    "job": "CRP",
    "rlvl": 755,
    "work": 8900,
    "quality": 23000,
    "durability": 40,
    "tag": "시간제 3 - 3",
    "group": "시간제 3",
    "category": "시간제"
  },
  {
    "region": "paenna",
    "missionId": 586,
    "missionName": "EX+: 수지 결정 정제 검증 3",
    "job": "CRP",
    "rlvl": 755,
    "work": 12000,
    "quality": 32300,
    "durability": 65,
    "tag": "시간제 3 - 3",
    "group": "시간제 3",
    "category": "시간제"
  },
  {
    "region": "oizys",
    "missionId": 1059,
    "missionName": "EX: 반출용 자재 대량 생산 지원",
    "job": "CRP",
    "rlvl": 727,
    "work": 2300,
    "quality": 24700,
    "durability": 70,
    "tag": "A-EX 3",
    "group": "A-EX 3",
    "category": "A-EX"
  },
  {
    "region": "oizys",
    "missionId": 1060,
    "missionName": "EX: 발굴 필수품 조달",
    "job": "CRP",
    "rlvl": 728,
    "work": 9700,
    "quality": 17300,
    "durability": 70,
    "tag": "A-EX 2",
    "group": "A-EX 2",
    "category": "A-EX"
  },
  {
    "region": "oizys",
    "missionId": 1061,
    "missionName": "EX: 발굴 현장 비품 지원",
    "job": "CRP",
    "rlvl": 729,
    "work": 8500,
    "quality": 19500,
    "durability": 60,
    "tag": "A-EX",
    "group": "A-EX",
    "category": "A-EX"
  },
  {
    "region": "oizys",
    "missionId": 1062,
    "missionName": "EX: 해변 휴가용품 개발",
    "job": "CRP",
    "rlvl": 721,
    "work": 6700,
    "quality": 14200,
    "durability": 50,
    "tag": "날씨제 1",
    "group": "날씨제 1",
    "category": "날씨제"
  },
  {
    "region": "oizys",
    "missionId": 1063,
    "missionName": "EX+: 행성 자원 활용 검증",
    "job": "CRP",
    "rlvl": 751,
    "work": 1600,
    "quality": 21000,
    "durability": 40,
    "tag": "시간제 1",
    "group": "시간제 1",
    "category": "시간제"
  },
  {
    "region": "oizys",
    "missionId": 1063,
    "missionName": "EX+: 행성 자원 활용 검증",
    "job": "CRP",
    "rlvl": 756,
    "work": 8200,
    "quality": 28300,
    "durability": 70,
    "tag": "시간제 1",
    "group": "시간제 1",
    "category": "시간제"
  },
  {
    "region": "oizys",
    "missionId": 1064,
    "missionName": "EX+: 식물 자원 고도 가공",
    "job": "CRP",
    "rlvl": 751,
    "work": 7200,
    "quality": 22600,
    "durability": 80,
    "tag": "날씨제 2",
    "group": "날씨제 2",
    "category": "날씨제"
  },
  {
    "region": "oizys",
    "missionId": 1065,
    "missionName": "EX+: 재생 에너지 연료 검증",
    "job": "CRP",
    "rlvl": 757,
    "work": 7500,
    "quality": 21000,
    "durability": 35,
    "tag": "시간제 2",
    "group": "시간제 2",
    "category": "시간제"
  },
  {
    "region": "oizys",
    "missionId": 1065,
    "missionName": "EX+: 재생 에너지 연료 검증",
    "job": "CRP",
    "rlvl": 757,
    "work": 9800,
    "quality": 27900,
    "durability": 50,
    "tag": "시간제 2",
    "group": "시간제 2",
    "category": "시간제"
  },
  {
    "region": "oizys",
    "missionId": 1066,
    "missionName": "EX+: 재생 에너지 연료 검증 2",
    "job": "CRP",
    "rlvl": 758,
    "work": 8000,
    "quality": 22000,
    "durability": 35,
    "tag": "시간제 2 - 2",
    "group": "시간제 2",
    "category": "시간제"
  },
  {
    "region": "oizys",
    "missionId": 1066,
    "missionName": "EX+: 재생 에너지 연료 검증 2",
    "job": "CRP",
    "rlvl": 758,
    "work": 11000,
    "quality": 29100,
    "durability": 60,
    "tag": "시간제 2 - 2",
    "group": "시간제 2",
    "category": "시간제"
  },
  {
    "region": "oizys",
    "missionId": 1067,
    "missionName": "EX+: 재생 에너지 연료 검증 3",
    "job": "CRP",
    "rlvl": 759,
    "work": 9000,
    "quality": 23000,
    "durability": 50,
    "tag": "시간제 2 - 3",
    "group": "시간제 2",
    "category": "시간제"
  },
  {
    "region": "oizys",
    "missionId": 1067,
    "missionName": "EX+: 재생 에너지 연료 검증 3",
    "job": "CRP",
    "rlvl": 759,
    "work": 12500,
    "quality": 33500,
    "durability": 70,
    "tag": "시간제 2 -3",
    "group": "시간제 2",
    "category": "시간제"
  }
];