const RECIPES_OIZYS = [
  {
    "region": "oizys",
    "missionId": 1059,
    "missionName": "EX: 반출용 자재 대량 생산 지원",
    "job": "CRP",
    "rlvl": 727,
    "work": 2300,
    "quality": 24700,
    "durability": 70,
    "tag": "A-EX 3",
    "group": "A-EX 3",
    "category": "A-EX",
    "isSub": false
  },
  {
    "region": "oizys",
    "missionId": 1060,
    "missionName": "EX: 발굴 필수품 조달",
    "job": "CRP",
    "rlvl": 728,
    "work": 9700,
    "quality": 17300,
    "durability": 70,
    "tag": "A-EX 2",
    "group": "A-EX 2",
    "category": "A-EX",
    "isSub": false
  },
  {
    "region": "oizys",
    "missionId": 1061,
    "missionName": "EX: 발굴 현장 비품 지원",
    "job": "CRP",
    "rlvl": 729,
    "work": 8500,
    "quality": 19500,
    "durability": 60,
    "tag": "A-EX",
    "group": "A-EX",
    "category": "A-EX",
    "isSub": false
  },
  {
    "region": "oizys",
    "missionId": 1062,
    "missionName": "EX: 해변 휴가용품 개발",
    "job": "CRP",
    "rlvl": 721,
    "work": 6700,
    "quality": 14200,
    "durability": 50,
    "tag": "날씨제 1",
    "group": "날씨제 1",
    "category": "날씨제",
    "isSub": false
  },
  {
    "region": "oizys",
    "missionId": 1063,
    "missionName": "EX+: 행성 자원 활용 검증",
    "job": "CRP",
    "rlvl": 751,
    "work": 1600,
    "quality": 21000,
    "durability": 40,
    "tag": "시간제 1",
    "group": "시간제 1",
    "category": "시간제",
    "isSub": true
  },
  {
    "region": "oizys",
    "missionId": 1063,
    "missionName": "EX+: 행성 자원 활용 검증",
    "job": "CRP",
    "rlvl": 756,
    "work": 8200,
    "quality": 28300,
    "durability": 70,
    "tag": "시간제 1",
    "group": "시간제 1",
    "category": "시간제",
    "isSub": false
  },
  {
    "region": "oizys",
    "missionId": 1064,
    "missionName": "EX+: 식물 자원 고도 가공",
    "job": "CRP",
    "rlvl": 751,
    "work": 7200,
    "quality": 22600,
    "durability": 80,
    "tag": "날씨제 2",
    "group": "날씨제 2",
    "category": "날씨제",
    "isSub": false
  },
  {
    "region": "oizys",
    "missionId": 1065,
    "missionName": "EX+: 재생 에너지 연료 검증",
    "job": "CRP",
    "rlvl": 757,
    "work": 7500,
    "quality": 21000,
    "durability": 35,
    "tag": "시간제 2",
    "group": "시간제 2",
    "category": "시간제",
    "isSub": true
  },
  {
    "region": "oizys",
    "missionId": 1065,
    "missionName": "EX+: 재생 에너지 연료 검증",
    "job": "CRP",
    "rlvl": 757,
    "work": 9800,
    "quality": 27900,
    "durability": 50,
    "tag": "시간제 2",
    "group": "시간제 2",
    "category": "시간제",
    "isSub": false
  },
  {
    "region": "oizys",
    "missionId": 1066,
    "missionName": "EX+: 재생 에너지 연료 검증 2",
    "job": "CRP",
    "rlvl": 758,
    "work": 8000,
    "quality": 22000,
    "durability": 35,
    "tag": "시간제 2 - 2",
    "group": "시간제 2",
    "category": "시간제",
    "isSub": true
  },
  {
    "region": "oizys",
    "missionId": 1066,
    "missionName": "EX+: 재생 에너지 연료 검증 2",
    "job": "CRP",
    "rlvl": 758,
    "work": 11000,
    "quality": 29100,
    "durability": 60,
    "tag": "시간제 2 - 2",
    "group": "시간제 2",
    "category": "시간제",
    "isSub": false
  },
  {
    "region": "oizys",
    "missionId": 1067,
    "missionName": "EX+: 재생 에너지 연료 검증 3",
    "job": "CRP",
    "rlvl": 759,
    "work": 9000,
    "quality": 23000,
    "durability": 50,
    "tag": "시간제 2 - 3",
    "group": "시간제 2",
    "category": "시간제",
    "isSub": true
  },
  {
    "region": "oizys",
    "missionId": 1067,
    "missionName": "EX+: 재생 에너지 연료 검증 3",
    "job": "CRP",
    "rlvl": 759,
    "work": 12500,
    "quality": 33500,
    "durability": 70,
    "tag": "시간제 2 -3",
    "group": "시간제 2",
    "category": "시간제",
    "isSub": false
  }
];
